### ISSUE TITLE
Error Installing with Go

### ISSUE THREAD

**Issue by ProfessorManhattan** [ariasmn/ugm#2]
Hey, I'm running into the following issue:

```
❯ go install github.com/ariasmn/ugm@latest
package github.com/ariasmn/ugm
	imports github.com/ariasmn/ugm/internal/tui
	imports github.com/ariasmn/ugm/internal/tui/group
	imports github.com/ariasmn/ugm/groupparser: build constraints exclude all Go files in /Users/xxx/.local/share/go/pkg/mod/github.com/ariasmn/ugm@v1.2.0/groupparser
package github.com/ariasmn/ugm
	imports github.com/ariasmn/ugm/internal/tui
	imports github.com/ariasmn/ugm/internal/tui/user
	imports github.com/ariasmn/ugm/userparser: build constraints exclude all Go files in /Users/xxx/.local/share/go/pkg/mod/github.com/ariasmn/ugm@v1.2.0/userparser
```

Any idea on how to resolve? Also, it would be great if this was published on Homebrew. Thanks!

**Comment by ariasmn** [comment]
@ProfessorManhattan Hi!

I guess that, since you are asking to get this published on Homebrew, you are running MacOS. This is a problem since `ugm` can't work under MacOS, as you can read in the [README](https://github.com/ariasmn/ugm#notes)

The error that you are seeing is related to the build constraints, which I included in both the `groupparser` and `userparser` packages to avoid problems in case another dev wanted to use them:
https://github.com/ariasmn/ugm/blob/6b5d59b49d852a7b7798116ef076b152cfe65815/groupparser/groupparser.go#L1-L2

Sadly, I'm not a MacOS user, so I don't know if there is any other similar TUI application for MacOS. :disappointed: 

I'm closing this. Please let me know if you have any other question!

**Comment by ProfessorManhattan** [comment]
Ahh thanks but Homebrew can work for Linux as well
